baseURL = 'https://chrishenzie.com/'
title = 'Chris Henzie'
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term']

[params]
  description = 'Maintainer and security advisor for containerd. Software engineer at Google, working upstream in Kubernetes.'

[outputs]
  home = ['HTML']
