baseURL = 'https://chrishenzie.com/'
title = 'Chris Henzie'
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term']

[params]
  description = 'Software engineer at Google working on Kubernetes and containerd.'

[outputs]
  home = ['HTML']
